language: java

dist: xenial
sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

jdk: openjdk11

addons:
  sonarcloud:
    organization: kani
    token:
      secure: $SONAR_TOKEN

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)