language: java

dist: xenial
sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

git:
  depth: false

jdk: openjdk11

addons:
  sonarcloud:
    organization: kani
    token:
      secure: $SONAR_TOKEN

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B

script:
  - mvn sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)
